### ISSUE TITLE
Admin Create Issues

### ISSUE THREAD

**Issue by guitarboy8d6** [davidjeddy/naabs2#11]
There seems to be an issue on basically every page where there is a create button in the admin area.

My notes:
index.php/user-details/create
Loads
An internal Server Error Occured

index.php/role/create
Loads
An internal server error occured

index.php/device-count/create
Loads
An internal server error occured

index.php/device/create
Loads
An internal server error occurred

Also maybe related, so note opening separate issue yet, but may need to based on investigation of the issue.
index.php/free-radius/defult
nothing loads
clicked Radius link in main menu bar

**Comment by davidjeddy** [comment]
corrected
