### ISSUE TITLE
Server 500 errors

### ISSUE THREAD

**Issue by guitarboy8d6** [davidjeddy/naabs2#12]
Naabs 2.0 Front End
In Chrome
When creating a user on the signup page, I get a Server error 500
In Firefox just get a blank page, looks like sending to index.php based on what is in address bar of browse

I don't seem to get this error anywhere else. however it seems to crash the system for the browser session. I ended up restarting apache because each time I did it the browser wouldn't browse anywhere in the that area of the server (frontend). I am unsure if any data got submitted to the db.

I doubled checked the apache config vhost settings, is there possibly a php loop or error of that nature?

**Comment by guitarboy8d6** [comment]
It may also be a session issue, I assume when you signup or log in it creates a session. It maybe getting hung up when it is trying to create or associate with the session as well.

It does look like some data submitted because I was able to login with one of my test accounts. I also see them when querying the user table with MySQL workbench.

**Comment by guitarboy8d6** [comment]
I looked in the apache log files and it does look like there is an undefined method or error in the method being called.

**Comment by davidjeddy** [comment]
should be corrected now
