### ISSUE TITLE
Backend views of Radius and Devices

### ISSUE THREAD

**Issue by guitarboy8d6** [davidjeddy/naabs2#14]
What exactly is the difference in these two views/pages. 

This is in the backend area
/index.php/free-radius/default
/index.php/device

Especially the radius page, it looks like I am looking at 2 expired devices, but how do I know what account they belong to.

The device page does show a userID of 1 so I guess through other views I can find the user that has a user ID of 1.

Is there a way to link them up better and flow better.

Like search user/see view of users, and then click a link that will show me all of their devices? It would be nice if on that page I could manually add and take away devices that are tied to that user.

I am not 100% sure what I am looking at or how it all correlates.

Can you please explain the methods more? And define the differences in the views?

**Comment by davidjeddy** [comment]
RadCheck:
Purpose:Data in the radius server table, limited by attribute 'expiration'.
Change: 'Primary Email' should ready 'Username', have the username as a link to the user view page

Device:
Purpose: Device to User correlation 
Change: User ID can be replaced with account username, again linked to user view page

On `/user-details/view?id={ID}` ( the user view page) we can add a list of user devices. Adding/Editing the device ON that page is a bit much, but we could link to the device edit form page easily to allow admin users to add / edit a user's device much easier.

**Comment by davidjeddy** [comment]
Iterated on menu system for Backend, should be easuer to understand. Still needs work but it is moving in the right direction
