### ISSUE TITLE
Bug - Backend create user

### ISSUE THREAD

**Issue by guitarboy8d6** [davidjeddy/naabs2#15]
On page /index.php/user-details/create in the backend, I filled out the form several different ways and when hitting submit got no errors, however nothing happened and no user was created or page reload or anything.

Looks like a bug.

**Comment by davidjeddy** [comment]
Could you provide a data set that was used where it did not operate correctly.

**Comment by davidjeddy** [comment]
Removed ability to create users in the back end, use frontend to create users.
