### ISSUE TITLE
Device to user account relation

### ISSUE THREAD

**Issue by davidjeddy** [davidjeddy/naabs2#9]
Need area or take part the that shows device information and allow people to add up to five devices, and take them away. We need to also store a device Nickname, or label so they can add something like marry's ipad to the device info. 

Move, Add, Change
Streaming devices such as Roku's, Smart TV's, etc. That do not have built in web browsers or ways to interact with the walled garden.

I would like to categorize devices by noraml device/Streaming device or something like that (open to suggestion/collaboration on it) There are settings on the RAS device for authentication based on MAC addresses. I would like to add the devices and if it is a streaming device they put in the MAC. I will have to give you the format it needs to be stored in and the username and pw that needs to be in the radcheck table is the MAC address. The walled garden will see the MAC and send it to the radius server and if the user and pw match the MAC it will allow it. So now people can use devices like this on the network.

---

This would require an entire rewrite of the how the user account, purchase, and radius systems interact. Recommend moving this to v3.

**Comment by guitarboy8d6** [comment]
Humm, what does a halfway point look like, just no payment needed for adding devices, or are you suggesting keeping current format 100%?

**Comment by guitarboy8d6** [comment]
After reading through other tickets it looks like there is another ticket that relates to this. Also not being able to handle streaming device s like smart TV's and rokus is going to make us take a hit for people signing up. It was a big question and a major request of end users. Devices that don't have built in web browsing can't authenticate with the walled garden form to put the username and pw in. So these devices in current form could never get access to internet. It has caused some to go elsewhere.

**Comment by guitarboy8d6** [comment]
See ticket #7 Account Signup Process. The comments there seem to be tied to this as well. I think we may have to move this restructure up to get in line with the best scenario for the end users, and support team.

**Comment by davidjeddy** [comment]
How have users authenticated streaming only devices before? Do the users know how to find/enter a device's MAC address? To many variable questions for this feature still.
